#!us/xbin/tamfan/perl
#!jangan recode gan, mikir pakai otak, udah di kasih tutorialnya juga di youtube gua, malah masih recode. lammer.
#mrtamfanx cyber team - tkj with prakasa_jr64
use Term::ANSIColor;
use MIME::Base64;
use if $^O eq "MSWin32", Win32::Console::ANSI;
$kasjakarta = localtime();
system('xdg-open https://www.youtube.com/channel/UCgxatcJPFCr2vWDj8e0rhsQ');
mrtamfanx();
tamfanx();
sub mrtamfanx {
	if ($^O =~ /MSWin32/) {system("mode con: cols=100 lines=29");system("cls"); }else { system("resize -s 28 87");system("clear"); }
	print color('bold cyan'),"┏━━━━━━━━━┓  ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n";
	print color('bold cyan'),"┃ ";
	print color('bold red'),"◯";
	print color('bold white')," ┅┅┅";
	print color('bold red')," ◯";
	print color('bold cyan')," ┃  ┃    ";
	print color('bold green'),"•";
	print color('bold cyan'),"Author ";
	print color('bold green'),": ";
	print color('bold white'),"MrTamfanX ";
	print color('bold red'),"- ";
	print color('bold white'),"Prakasa_Jr64";
	print color('bold green'),"•";
	print color('bold cyan'),"    ┃\n";
	print color('bold cyan'),"┠─────────┨  ┃";
	print color('bold green'),"  •";
	print color('bold white'),"My Team";
	print color('bold red')," Dan";
	print color('bold blue')," IG";
	print color('bold green')," :";
	print color('bold yellow')," MrTamfanX Cyber Team";
	print color('bold green'),"•";
	print color('bold cyan'),"  ┃\n";
	print color('bold cyan'),"┃";
	print color('bold white'),"█████████";
	print color('bold cyan'),"┣━━┫";
	print color('bold green')," •";
	print color('bold green'),"WhatsApp :";
	print color('bold white')," 0857";
	print color('bold red'),"-";
	print color('bold white'),"8041";
	print color('bold red'),"-";
	print color('bold white'),"1404 859";
	print color('bold red'),"-";
	print color('bold white'),"6634";
	print color('bold red'),"-";
	print color('bold white'),"6141";
	print color('bold green'),"•";
	print color('bold cyan')," ┃\n";
	print color('bold cyan'),"┃";
	print color('bold white'),"█████████";
	print color('bold cyan'),"┃  ┃";
	print color('bold green')," •";
	print color('bold blue'),"Facebook";
	print color('bold green')," :";
	print color('bold white')," Prakasa Jr";
	print color('bold blue')," IG";
	print color('bold green')," :";
	print color('bold white')," Prakasa_Jr64";
	print color('bold green'),"•";
	print color('bold cyan')," ┃\n";
	print color('bold cyan'),"┃";
	print color('bold white'),"█████████";
	print color('bold cyan'),"┣━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\n";
	print color('bold cyan'),"┃";
	print color('bold white'),"█████████";
	print color('bold cyan'),"┃  ┃";
	print color('bold green')," •";
	print color('bold cyan'),"Kunjungi FP";
	print color('bold red')," -";
	print color('bold blue')," FB";
	print color('bold green')," :";
	print color('bold yellow')," MrTamfanX Cyber Team";
	print color('bold green'),"•";
	print color('bold cyan')," ┃\n";
	print color('bold cyan'),"┃";
	print color('bold white'),"█████████";
	print color('bold cyan'),"┃  ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n";
	print color('bold cyan'),"┃";
	print color('bold white'),"█████████";
	print color('bold cyan'),"┃";
	print color('bold white'),"  [";
	print color('bold red'),"•";
	print color('bold white'),"]";
	print color('bold cyan')," Sekarang Jam";
	print color('bold green')," :";
	print color('bold yellow')," $kasjakarta\n";
	print color('bold cyan'),"┠─────────┨\n";
	print color('bold cyan'),"┃";
	print color('bold white'),"    ⭕";
	print color('bold cyan'),"   ┃\n";
	print color('bold cyan'),"┗━━━━━━━━━┛\n";
	print color('bold cyan'),"╾────────────────────────────────────────────────────────╼\n";
	print color('bold white'),"[";
	print color('bold green'),"•";
	print color('bold cyan'),"]";
	print color('bold yellow')," Terima Kasih Telah Memakai Tools Decod Base64 Kami";
	print color('bold red'),"...\n\n";
}
sub tamfanx {
	print color('bold white'),"[";
	print color('bold green'),"1";
	print color('bold white'),"]";
	print color('bold yellow')," Encode Base64\n";
	print color('bold white'),"[";
        print color('bold green'),"2";
        print color('bold white'),"]";
        print color('bold yellow')," Decode Base64\n\n";
	print color('bold white'),"[";
        print color('bold green'),"1";
        print color('bold white'),"]";
        print color('bold cyan')," Pilih Nomernya Boss ";
	print color('bold green'),": ";
	print color('bold white'),"";
	chomp($kaskas=<STDIN>);
	if($kaskas eq '1'){
	mrtamfanx();
	print color('bold white'),"[";
	print color('bold green'),"•";
	print color('bold white'),"] ";
	print color('bold cyan'),"Masukan Textnya ";
        print color('bold green'),": ";
	print color('bold yellow'),"";
        $akas1=<STDIN>;
	$mantap1 = $akas1;
        $ancol1 = encode_base64($mantap1);
	print color('bold white'),"[";
        print color('bold green'),"✓";
	print color('bold white'),"]";;
	print color('bold white')," Hasilnya Dari MrTamfanX ";
	print color('bold green'),": ";
        print color('bold yellow'),"$ancol1\n\n";
	print color('bold green'),"";
	}if($kaskas eq '2'){
	mrtamfanx();
	print color('bold white'),"[";
	print color('bold green'),"•";
        print color('bold white'),"] ";
        print color('bold cyan'),"Masukan Textnya ";
        print color('bold green'),": ";
        print color('bold yellow'),"";
        $akas2=<STDIN>;
        $mantap2 = $akas2;
	$ancol2 = decode_base64($mantap2);
	print color('bold white'),"[";
        print color('bold green'),"✓";
        print color('bold white'),"]";;
        print color('bold white')," Hasilnya Dari MrTamfanX ";
        print color('bold green'),": ";
        print color('bold yellow'),"$ancol2\n\n";
        print color('bold green'),"";
	}
}
